### ISSUE TITLE
No extra nodes for leafs

### ISSUE THREAD

**Issue by krystian50** [FluffyLabs/trie-visualiser#5]
There should be no extra "leaf nodes" - the leaf node is just the last node. IT should have a different color (like it has now). The tooltip should display the leaf information data (We need: "Key" and "Value Hash: " and "Value: " - this data might be missing in the lib now, will be added)

**Comment by krystian50** [comment]
@tomusdrw could you explain what do you mean by extra leaf node? I saw that every leaf has an extra parent before being connected with by another node with a sibling. Is that what you mean? I take it from the trie library. Any idea why it happens?
<img width="392" alt="image" src="https://github.com/user-attachments/assets/88e2a052-d00a-4c38-ada6-57bd0c410fdc">

**Comment by tomusdrw** [comment]
Yes. The last node is the `node.getNodeType() === NodeType.Leaf` or `node.getNodeType() === NodeType.EmbeddedLeaf` and I think that's the nodes `0x97` and `0x96` in your screenshot.

I suspect that what you do is that at this point you take `node.getKey()` and create an extra node that has the hash set to `node.getKey()` and the values to `node.getValue() or node.getValueHash()`. I suspect that because the `0x83` and `0x03` matches the keys of some input values.

That shouldn't be the case. The last displayed element should be the actual node and then this extra "leaf info" should be in the tooltip.

**Comment by tomusdrw** [comment]
Fixed already
